name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1      
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x     
          
      - name: Build
        run: |
          npm install
          npm run build:ci

      - name: Test
        run: npm run test:ci  
      
      - name: Deploy to Surge
        run: npx surge --project=./dist/shopping-site/ --domain=${{ secrets.SURGE_DOMAIN }} --token=${{ secrets.SURGE_TOKEN }}